### ISSUE TITLE
Deprecate in favor of node.

### ISSUE THREAD

**Issue by frank-dspeed** [robojones/create-path#1]
```
node -e 'require("fs").mkdirSync("./my/nested", { recursive: true })';
```

**Comment by robojones** [comment]
Would you be willing to create a PR? I will merge it asap.

**Comment by frank-dspeed** [comment]
I am preparing a PR already it is on list i am doing a bigger effort i am from the NodeJS Package Maintainance Group but i work a bit sloppy 👯 .

It is still experimental what is the right process to handle all that i guess till monday i did a clean pr for that.

**Comment by frank-dspeed** [comment]
- [x] - https://github.com/robojones/create-path/pull/2
- [x] - Needs testing did write it on github

**Comment by frank-dspeed** [comment]
Ich bin auch aus deutschland übrigens du warst deiner zeit weit vorraus 👍🏻

**Comment by robojones** [comment]
Sorry dass es so lange gedauert hat. Waren ein paar stressige Wochen. Falls ich irgendwie Zeit finde teste ich nachher den PR und publishe das Update.

**Comment by robojones** [comment]
So, jetzt ist alles fertig und published. Danke für den PR 🥇

**Comment by frank-dspeed** [comment]
Closed by: #2
